env:
  global:
    - TEST_DATABASE_URL=postgres://postgres@localhost/read_rust_test
    - MASTODON_BASE=https://botsin.space
    - MASTODON_CLIENT_ID=
    - MASTODON_CLIENT_SECRET=
    - MASTODON_REDIRECT=urn:ietf:wg:oauth:2.0:oob
    - MASTODON_TOKEN=
    - TWITTER_CONSUMER_KEY=
    - TWITTER_CONSUMER_SECRET=
    - TWITTER_ACCESS_KEY=
    - TWITTER_ACCESS_SECRET=
    - FEEDBIN_USERNAME=
    - FEEDBIN_PASSWORD=
matrix:
  include:
    - language: rust
      cache: cargo
      script:
        - cd rust
        - cargo test
      rust:
        - stable

    - language: crystal
      addons:
        chrome: stable
        postgresql: "11"
      services:
        - postgresql
      before_install:
        # Setup chromedriver for LuckyFlow
        - sudo apt-get install chromium-chromedriver curl

        # Install libstriptags
        - curl -OL https://releases.wezm.net/striptags/striptags_0.1.1-2_amd64.deb
        - sudo dpkg -i striptags_0.1.1-2_amd64.deb

        # Setup assets
        - cd crystal
        - yarn install
        - yarn prod
      script:
        - crystal spec
        - yarn run tsc
        # Uncomment the next line if you'd like Travis to check code formatting
        # - crystal tool format spec src --check
      cache:
        yarn: true
        directories:
          - crystal/bin/lucky
          - crystal/lib
          - crystal/.shards
