language: rust
cache: cargo
install: '[ "`cobalt --version`" == "Cobalt 0.11.1" ] || cargo install --force cobalt-bin'
script:
  - which cobalt || cargo test --verbose
  - make
rust:
  - stable
  - beta
matrix:
  allow_failures:
    - rust: beta
