[package]
name = "read-rust"
version = "0.1.0"
authors = ["Wesley Moore <wes@wezm.net>"]

[dependencies]
chrono = { version = "0.4.0", features = ['serde'] }
kuchiki = "0.6"
opengraph = "0.1"
reqwest = "0.8"
rss = "1.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.5", features = ['v4', 'serde'] }
